### ISSUE TITLE
Ghost files

### ISSUE THREAD

**Issue by aaaabbk** [lhjamieson/COSC401MajorProject201920#5]
Periodically, when adding and deleting a file, a file will appear to delete, but still shows up. Throws an error saying "File could not be deleted". Persists on relaunch, file doesn't exist in folder on disc.

**Comment by aaaabbk** [comment]
Folders behave weirdly when ghost files exist.

**Comment by MattHeitmann** [comment]
This issue happens because the DeleteAFile function (in controller) is not interacting with the database, but instead is only looking for the file on a local machine. What needs to happen is:
-Get the file name/id from the viewbag. This is the easiest way because the viewbag should already hold all the user data for their personal session
-Query the database using the name/id
-Remove the file from the database
-Update the database to reflect this change
-Refresh the page so that the file no longer appears

**Comment by MattHeitmann** [comment]
This delete bug might happen when someone uploads a file that has the same name as a file that already exists on the database.

**Comment by TWalkerSMCM** [comment]
Ghost files should be fixed, duplicate files are no fixed as are the delete and rename functions that contributed to this problem.
